language: python

python:
  - 3.6

env:
  - DJANGO=1.8

before_install:
  - export DJANGO_SETTINGS_MODULE=simple_backend.settings

install:
  - pip install -r requirements.txt

script:
  - python manage.py test