language: generic

sudo: required
dist: trusty

services:
  - docker

jobs:
  include:
  - stage: build docker image
    script:
      - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
      - docker build -t registry.heroku.com/simple-backend/web .
      - docker push registry.heroku.com/simple-backend/web
  - stage: unit tests againt latest docker image
    script:
      - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
      - docker-compose -f docker-compose.test.yml pull
      - docker-compose -f docker-compose.test.yml up --abort-on-container-exit
  - stage: deploy application to production
    script: skip
    deploy:
      provider: heroku
      api_key: $HEROKU_TOKEN
      app: simple-backend
  - stage: test production
    script: 'curl https://simple-backend.herokuapp.com/'
