language: generic

sudo: required
dist: trusty

services:
  - docker

jobs:
  include:
  - stage: build docker image
    script:
      - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
      - docker build -t registry.heroku.com/powerful-taiga-71470/web .
      - docker push registry.heroku.com/powerful-taiga-71470/web
  - stage: unit tests
    script:
      - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
      - docker-compose -f docker-compose.test.yml up
  - stage: deploy to production
    script: skip
    deploy:
      provider: heroku
      api_key: $HEROKU_TOKEN
      app: powerful-taiga-71470
  - stage: test production
    script: 'curl https://powerful-taiga-71470.herokuapp.com/'
