# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 18:46
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def loadfixture(apps, schema_editor):
    call_command('loaddata', 'initial_data.json')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
